### ISSUE TITLE
Suggest putting a metrics sample in README

### ISSUE THREAD

**Issue by deanmax** [elonzh/clash_exporter#1]
Is this project ready for use? Perhaps a quick examples in README would help people get a rough idea about this exporter.

**Comment by elonzh** [comment]
I will update the README later, thanks for your feedback!

Metric sample:

```
# HELP clash_connection_download_total Number of bytes that downloaded by clash.
# TYPE clash_connection_download_total counter
clash_connection_download_total 1.4203388005e+10
# HELP clash_connection_upload_total Number of bytes that uploaded by clash.
# TYPE clash_connection_upload_total counter
clash_connection_upload_total 2.66612201e+08
# HELP clash_exporter_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which clash_exporter was built.
# TYPE clash_exporter_build_info gauge
clash_exporter_build_info{branch="HEAD",goversion="go1.16.4",revision="f9eb587c77ab55e5a7fd09ab6ecad1f1f88f210b",version="0.0.2"} 1
# HELP clash_exporter_scrapes_total Current total Clash scrapes.
# TYPE clash_exporter_scrapes_total counter
clash_exporter_scrapes_total 97818
# HELP clash_proxy_delay Proxy delay.
# TYPE clash_proxy_delay gauge
clash_proxy_delay{name="PH1",provider="monocloud",type="Shadowsocks"} 233
clash_proxy_delay{name="🇨🇳 Relay-TW1",provider="monocloud",type="Shadowsocks"} 328
clash_proxy_delay{name="🇨🇳 Relay-TW2",provider="monocloud",type="Shadowsocks"} 324
clash_proxy_delay{name="🇯🇵 Relay-JP1",provider="monocloud",type="Shadowsocks"} 277
clash_proxy_delay{name="🇯🇵 Relay-JP2",provider="monocloud",type="Shadowsocks"} 65535
clash_proxy_delay{name="🇯🇵 日本 08",provider="amytelecom",type="Shadowsocks"} 155
clash_proxy_delay{name="🇸🇬 新加坡 01",provider="amytelecom",type="Shadowsocks"} 213
clash_proxy_delay{name="🇸🇬 新加坡 04",provider="amytelecom",type="Shadowsocks"} 216
clash_proxy_delay{name="🇺🇸 Relay-US1",provider="monocloud",type="Shadowsocks"} 65535
clash_proxy_delay{name="🇺🇸 Relay-US2",provider="monocloud",type="Shadowsocks"} 856
clash_proxy_delay{name="🇺🇸 美国 01",provider="amytelecom",type="Shadowsocks"} 310
# HELP clash_up Was the last scrape of Clash successful.
# TYPE clash_up gauge
clash_up 1
# HELP clash_version_info Clash version info.
# TYPE clash_version_info gauge
clash_version_info{premium="false",version="v1.7.0"} 1
...
```

Dashboard:

![image](https://user-images.githubusercontent.com/8749411/150261772-0ac4ff6d-23a3-4f87-a02b-904988f0dc7b.png)

**Comment by deanmax** [comment]
Thanks! Dashboard looks great! Is that dashboard constructed using all metrics available through this repo?

**Comment by deanmax** [comment]
Also would be greater if there're metrics for data used for each proxy

**Comment by elonzh** [comment]
> Also would be greater if there're metrics for data used for each proxy

This is impossible cause Clash doesn't provide such an API.

**Comment by deanmax** [comment]
Not sure if you're aware of this clash dashboard project - https://github.com/haishanh/yacd
They seem to be able to provide data usage on each host visited. I believe they're using Clash API.
<img width="1766" alt="Screen Shot 2022-01-20 at 16 47 11" src="https://user-images.githubusercontent.com/3320547/150304565-90e9f308-f487-433a-a70b-e540ef33e43d.png">

**Comment by elonzh** [comment]
1. Connections are real-time snapshots, your will lose everything when the connection is closed. 
2. Clash doesn't provide proxy traffic metrics.

**Comment by deanmax** [comment]
> 1. Connections are real-time snapshots, your will lose everything when the connection is closed.
> 
>     2. Clash doesn't provide proxy traffic metrics.

Understood. I was just wondering if, given enough short scrape interval, prometheus can grab those data and store in tsdb. But this is somewhat against the best practise of prometheus usage. Thanks for the update!

Btw, are you able to publish your grafana dashboard?
