### ISSUE TITLE
大佬可以分享一下grafana面板吗？

### ISSUE THREAD

**Issue by fengmikaelson** [elonzh/clash_exporter#2]
求分享一下面板

**Comment by elonzh** [comment]
https://github.com/elonzh/clash_exporter/blob/main/dashboard.json

**Comment by fengmikaelson** [comment]
> https://github.com/elonzh/clash_exporter/blob/main/dashboard.json

感谢大佬回复。
另外想问下，流量统计这一块没数据，是因为缺少了什么吗？还是要premium版本才支持？

**Comment by elonzh** [comment]
不需要 premium 版本, 至于流量统计数据你可以直接调 clash 的 API，以及查询下 prometheus 数据调试一下，我没法给出结论
